window.lang = {
    'locale': "en",
    'locale_date_string': "dddd MMMM DD",
    'locale_time_format': "h:mm A",
    'now_playing': "NOW PLAYING",
    'coming_soon': "COMING SOON",
    'coming_soon_to': "Coming Soon to",
    'more': "MORE",
    'book': "Reserve",
    'trailer': "TRAILER",
    'directed_by': "Directed by",
    'starring': "Starring",
    'language': "Language",
    'menu': "MENU",
    'find_us': "FIND US",
    'welcome_to': "Welcome to",
    'closest_cinema': "Your closest cinema is",
    'select_location': "Please select your location.",
    'continue': "CONTINUE",
    'cinema_selector_text': "If this isn’t the location you want, no drama, please select from the below.",
    'see_all': "SEE ALL",
    'at': "at",
    'undated': "Undated",
    'no_release_date': "No Release Date",
    'minutes': "mins",
    'rated': "Rated",
    'tbc': "TBC",
    'read_more': "Read more...",
    'tweet': "Tweet",
    'share': "Share",
    'times_and_tickets': "Times &amp; Tickets",
    'movie_times_and_tickets': "movie times &amp; tickets",
    'by_day': "BY DAY",
    'by_movie': "BY TITLE",
    'newest_first': "Newest first",
    'order_alphabetically': "A-Z",
    'order_by_session': "By showtimes",
    'print': "PRINT",
    'movie_times': "Movie Times",
    'advance_tickets': "ADVANCE TICKETS",
    '404_communicate': "<h1>404 - Page not found.</h1><p>Looks like the page you’re looking for is unavailable.</p><p>Please head back to our <a href="/">homepage</a>.</p>",
    'today': "Today",
    'no_sessions': "No Session Times Available",
    'no_movies_today': "No movies left today, try tomorrow.",
    'sessions_key': "SESSIONS KEY. ",
    'timezone': "Pacific/Auckland",
}